### ISSUE TITLE
Creating the docker image builds different version

### ISSUE THREAD

**Issue by peschmae** [qn7o/jinja2-live-parser#11]
In the dockerfile the repository gets cloned from https://github.com/sahilsk/jinja2-live-parser instead of https://github.com/qn7o/jinja2-live-parser

Additionally the sed command that's present, no longer works, since the app.run command now takes arguments passed in from the config.py

I'd advise to change the repository URL to https://github.com/qn7o/jinja2-live-parser and the sed command to 
`
RUN sed -i 's/host=config.HOST/host="0.0.0.0"/g' parser.py
`

This way the most up to date version from https://github.com/qn7o/jinja2-live-parser is build when the docker command is called, and using the adjusted sed command it also works.

I've already implemented those changes in "https://github.com/peschmae/jinja2-live-parser/blob/master/Dockerfile" but there I've also changed the jinja version to 2.8.0, since I'm dependant on that.

If you don't deem it necessary to have  a working docker build, feel free to close this issue.

**Comment by qn7o** [comment]
(and sorry for the delay)
