### ISSUE TITLE
License

### ISSUE THREAD

**Issue by argysamo** [qn7o/jinja2-live-parser#13]
Dear @qn7o ,
Congratulations for this awesome project. 
I find it extremely useful and I want to re-use it in a Flask project I am working on. 
Do you have any thoughts about the license? 
In the current state (no license) no one can *legally* re-use it. 
Here is an excerpt from [GitHub](https://help.github.com/articles/licensing-a-repository/):

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

**Comment by qn7o** [comment]
Hello @argysamo, thanks for the kind words and suggestion.  
You're right, and I'll add a licence asap.

Please apologize my super-late answer.

**Comment by argysamo** [comment]
Great news - thanks so much!
I will let you know, when I will re-use your software 😃

**Comment by qn7o** [comment]
Great, please do ! :)
